export const initialChats = [
  {
    id: 1,
    name: 'Nindy Lendika',
    lastMessage: "How're you doing today?",
    time: '2 PM',
    image: require('../assets/images/3.jpg'),
    isOnline: true,
    unreadCount: 2,
  },
  {
    id: 2,
    name: 'Sarah Johnson',
    lastMessage: 'See you tomorrow!',
    time: '1:30 PM',
    image: require('../assets/images/2.jpg'),
    isOnline: true,
    unreadCount: 0,
  },
  {
    id: 3,
    name: 'Mike Wilson',
    lastMessage: 'Thanks for the help',
    time: '12:45 PM',
    image: require('../assets/images/5.jpg'),
    isOnline: false,
    unreadCount: 0,
  },
  {
    id: 4,
    name: 'Emma Davis',
    lastMessage: "That sounds great!",
    time: '11:20 AM',
    image: require('../assets/images/4.jpg'),
    isOnline: true,
    unreadCount: 1,
  },
  {
    id: 5,
    name: 'James Brown',
    lastMessage: "I'll check it out",
    time: 'Yesterday',
    image: require('../assets/images/1.jpg'),
    isOnline: false,
    unreadCount: 0,
  },
];